name: Build GMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3
    - name: Generate GMake project files
      run: |
        chmod +x ./vendor/premake/premake5
        chmod +x ./GenerateProj_GMake2.sh
        ./GenerateProj_GMake2.sh
      shell: bash
    - name: make
      run: make
